---
name: checks on Pull Request
"on":
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  gitlint:
    name: Run gitlint checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirements.lock
      - name: Run gitlint on CI with pre-commit
        run: >-
          gitlint --commits origin/${{ github.event.pull_request.base.ref
          }}..HEAD
  check-same-go-toolset:
    name: Check the same Go Toolset image is used everywhere
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run check-same-go-toolset script
        run: >-
          bash chore-scripts/check-same-go-toolset.sh
